### PR TITLE
Mage improvements

### PR DESCRIPTION
**Pull request by kadeshar**
- Mage improvement: Mage cast Blast wave only against player
- Mage improvement: Excluded Blast wave and Dragon's breath from vanilla compilation

obraz
obraz

### CODE REVIEW

**Comment by celguar** [comment]
"and certain PvE situations". I don't see why we should limit bots like that

**Comment by celguar** [comment]
If you exclude blast wave that has alternative - frost nova, you need to make sure that frost nova is still there for fire mages to use when enemy is close. Still I don't agree we should exclude blast wave. If you took pvp specced fire mage to dungeon and don't want it to cast blast wave, use "ss [Blast Wave]" to disable it

**Comment by celguar** [comment]
Any thoughts?

**Comment by mostlikely4r** [comment]
> Any thoughts?

Hey Celg, I asked for this since it was mentioned mage bots used blast wave the moment any mob gets close. The same happens with aoe fears which trigger from any player or mob gets within range.

I assumed this was incorrect for pve situations but ok for pvp. For pve I assumed an aoe trigger (multiple mobs near) would be better.
Alas I don't know mages well enough to judge it either way.

@celguar is this change best expanded more or reverted?

**Comment by kadeshar** [comment]
1. Pve fire mages dont even learn blast wave talent
2.  Real players feedback about blast wave in pve. Tbh i wanted to ask about bots and glyphs. They use it?
obraz
obraz
3, Finally i think better use command "do Blast Wave" in "certain PvE situation" than put that in default pve rotation

**Comment by celguar** [comment]
k it makes some sense

**Pull request merged**
